stages:
  - test

variables:
  PYTHON_VERSION: "3.7"
  VENV_DIR: "myenv"

test:
  stage: test
  image: python:3.7
  before_script:
    - python -m venv $VENV_DIR
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest -q --tb=short
  only:
    - branches
    - merge_requests
    - triggers

